name: Keep Railway App Alive

on:
  schedule:
    # Ejecutar cada 25 minutos para mantener la app despierta
    - cron: '*/25 * * * *'
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Railway App
        run: |
          curl -f https://tu-app-railway.railway.app/health || echo "App is sleeping, pinging..."
          curl -X GET https://tu-app-railway.railway.app/health
